version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ACCOUNT_ID: "495456621615"
    IMAGE_REPO_NAME: sample/frontend
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws sts get-caller-identity
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 495456621615.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t sample/frontend:latest -f frontend/Dockerfile frontend
      - docker tag sample/frontend:latest 495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/frontend:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/frontend:latest
      - printf '[{"name":"poc","imageUri":"%s"}]' "495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/frontend:latest" > frontend-imagedefinitions.json
  
  

artifacts:
  files:
    - frontend-imagedefinitions.json