version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ACCOUNT_ID: "495456621615"
    IMAGE_REPO_NAME: sample/backend
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws sts get-caller-identity
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 495456621615.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t sample/backend:latest -f backend/Dockerfile backend
      - docker tag sample/backend:latest 495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/backend:latest

  # post_build:
  #   commands:
  #     - echo "Pushing Docker image to Amazon ECR..."
  #     - docker push 495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/backend:latest
  #     - printf '[{"name":"backend","495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/backend:latest":"%s"}]' "495456621615.dkr.ecr.ap-south-1.amazonaws.com/sample/backend:latest" > imagedefinitions.json
  post_build:
  commands:
    - echo "Pushing Docker image to Amazon ECR..."
    - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    - printf '[{"name":"backend","imageUri":"%s"}]' "$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imageDefinations.json